(function() {var implementors = {};
implementors['rust_htslib'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bam/record/struct.Record.html' title='rust_htslib::bam::record::Record'>Record</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bam/pileup/struct.Pileups.html' title='rust_htslib::bam::pileup::Pileups'>Pileups</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bam/struct.Reader.html' title='rust_htslib::bam::Reader'>Reader</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bam/struct.IndexedReader.html' title='rust_htslib::bam::IndexedReader'>IndexedReader</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bam/struct.Writer.html' title='rust_htslib::bam::Writer'>Writer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bcf/record/struct.Record.html' title='rust_htslib::bcf::record::Record'>Record</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bcf/header/struct.Header.html' title='rust_htslib::bcf::header::Header'>Header</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bcf/struct.Reader.html' title='rust_htslib::bcf::Reader'>Reader</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='rust_htslib/bcf/struct.Writer.html' title='rust_htslib::bcf::Writer'>Writer</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
